(function(){
  const APP='https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
  const AUTH='https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
  const FS='https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
  const FN='https://www.gstatic.com/firebasejs/12.2.1/firebase-functions.js';
  const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
  const money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2});
  let booted=false,isAdmin=false,adminCache=null;
  async function mods(){return Promise.all([import(APP),import(AUTH),import(FS),import(FN)])}
  async function authState(force=false){const [a,am]=await Promise.all([import(APP),import(AUTH)]);const auth=am.getAuth(a.getApps()[0]);const u=auth.currentUser;if(!u)return {auth,user:null,admin:false};const r=await am.getIdTokenResult(u,force);return {auth,user:u,admin:r.claims.admin===true}}
  async function call(name,data){const [a,am,,fm]=await mods();const app=a.getApps()[0];const f=fm.getFunctions(app,'asia-south1');return (await fm.httpsCallable(f,name)(data||{})).data}
  function openModal(html,id='bptFeatureModal'){
    document.querySelectorAll('.app-drawer,.modal-back').forEach(x=>x.remove());
    const b=document.createElement('div');b.className='modal-back open';b.id=id;b.innerHTML='<div class="modal" style="max-width:760px;max-height:88vh;overflow:auto">'+html+'</div>';document.body.appendChild(b);return b;
  }
  function closeOnBackdrop(b){b.onclick=e=>{if(e.target===b)b.remove()};b.querySelector('[data-close]')?.addEventListener('click',()=>b.remove())}
  async function markSeen(id){try{const [a,,fs]=await mods();const st=await authState();if(!st.user)return;const db=fs.getFirestore(a.getApps()[0]);await fs.setDoc(fs.doc(db,'users',st.user.uid,'mailboxState',id),{readAt:fs.serverTimestamp()},{merge:true})}catch(e){}}
  async function mailbox(){
    const b=openModal('<button class="close" data-close type="button">×</button><h3>📬 Mailbox</h3><p style="color:#8997aa;font-size:12px">Announcements and important updates.</p><div id="bptMailboxList" style="display:grid;gap:10px;margin-top:16px"><div style="color:#8997aa">Loading…</div></div>');closeOnBackdrop(b);
    try{const [a,,fs]=await mods();const st=await authState();if(!st.user)throw Error('not signed in');const db=fs.getFirestore(a.getApps()[0]);const [as,rs]=await Promise.all([fs.getDocs(fs.query(fs.collection(db,'announcements'),fs.orderBy('createdAt','desc'),fs.limit(30))),fs.getDocs(fs.collection(db,'users',st.user.uid,'mailboxState'))]);const read=new Set(rs.docs.map(x=>x.id));const list=document.getElementById('bptMailboxList');if(!as.size){list.innerHTML='<div style="padding:24px;text-align:center;color:#8997aa">No announcements yet.</div>';return}list.innerHTML=as.docs.map(d=>{const x=d.data()||{};const date=x.createdAt?.toDate?x.createdAt.toDate().toLocaleString('en-IN'):'';return `<article data-mail="${esc(d.id)}" style="padding:14px;border:1px solid #243247;border-radius:14px;background:#0e1927"><div style="display:flex;justify-content:space-between;gap:10px"><b>${esc(x.title||'Announcement')}</b>${read.has(d.id)?'':'<span style="font-size:10px;color:#55d6a0">● NEW</span>'}</div><div style="white-space:pre-wrap;margin-top:8px;line-height:1.55;color:#c8d1dd;font-size:13px">${esc(x.body||'')}</div><small style="display:block;margin-top:10px;color:#718096">${esc(date)}</small></article>`}).join('');list.querySelectorAll('[data-mail]').forEach(el=>{if(!read.has(el.dataset.mail))el.addEventListener('click',()=>markSeen(el.dataset.mail),{once:true})})}catch(e){document.getElementById('bptMailboxList').innerHTML='<div style="color:#ff8d8d">Could not load mailbox.</div>'}
  }
  async function sendAnnouncement(){
    const b=openModal('<button class="close" data-close type="button">×</button><h3>📢 Send Announcement</h3><p style="color:#8997aa;font-size:12px">This message will be delivered to every signed-in user.</p><label style="display:block;margin-top:16px">Title<input id="bptAnnTitle" maxlength="120" placeholder="Important update"></label><label style="display:block;margin-top:12px">Message<textarea id="bptAnnBody" maxlength="4000" rows="7" placeholder="Write your announcement…" style="width:100%;resize:vertical"></textarea></label><div class="modal-actions"><button class="secondary" data-close type="button">Cancel</button><button id="bptAnnSend" class="primary" type="button">Send to everyone</button></div>');closeOnBackdrop(b);b.querySelector('#bptAnnSend').onclick=async()=>{const t=b.querySelector('#bptAnnTitle').value.trim(),body=b.querySelector('#bptAnnBody').value.trim();if(!t||!body)return alert('Enter a title and message.');const btn=b.querySelector('#bptAnnSend');btn.disabled=true;btn.textContent='Sending…';try{await call('sendAnnouncement',{title:t,body});alert('Announcement sent to all users.');b.remove()}catch(e){alert(e.message||'Could not send announcement.');btn.disabled=false;btn.textContent='Send to everyone'}};
  }
  async function userDetails(uid){
    try{const r=await call('getAdminUser',{uid});const u=r.user||{};const trades=r.trades||[];const profit=trades.reduce((n,x)=>n+(Number(x.sale??0)-Number(x.cost??0)),0);const b=openModal(`<button class="close" data-close type="button">×</button><h3>${esc(u.username||'User')}</h3><p style="color:#8997aa;font-size:12px">${esc(u.email)} · ${u.disabled?'Disabled':'Active'}</p><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:14px 0"><div class="bpt-stat"><small>Trades</small><b>${trades.length}</b></div><div class="bpt-stat"><small>Booked profit</small><b>${money(profit)}</b></div><div class="bpt-stat"><small>Charges</small><b>${r.charges?.length||0}</b></div></div><h4>Trade history</h4><div style="overflow:auto"><table style="width:100%;font-size:11px"><thead><tr><th>Stock</th><th>Buy</th><th>Sell</th><th>Profit</th></tr></thead><tbody>${trades.length?trades.map(x=>`<tr><td>${esc(x.ticker||x.stock||'—')}</td><td>${esc(x.buyDate||'—')}</td><td>${esc(x.sellDate||'—')}</td><td>${money(Number(x.sale??0)-Number(x.cost??0))}</td></tr>`).join(''):'<tr><td colspan="4" style="text-align:center;color:#8997aa;padding:16px">No trades</td></tr>'}</tbody></table></div>`);closeOnBackdrop(b)}catch(e){alert(e.message||'Could not load user details.')}
  }
  async function toggleUser(uid,disabled){if(!confirm(disabled?'Disable this user? They will not be able to sign in.':'Enable this user?'))return;try{await call('setUserDisabled',{uid,disabled});adminCache=null;adminDashboard()}catch(e){alert(e.message||'Could not update user.')}}
  async function deleteUser(uid,name){if(!confirm(`Permanently delete ${name||'this user'} and their stored trades? This cannot be undone.`))return;try{await call('deleteUser',{uid});adminCache=null;adminDashboard()}catch(e){alert(e.message||'Could not delete user.')}}
  function renderUsers(list,container){const q=(container.querySelector('#bptUserSearch').value||'').trim().toLowerCase();const filtered=list.filter(u=>[u.username,u.email,u.uid].some(v=>String(v||'').toLowerCase().includes(q)));container.querySelector('#bptUserCount').textContent=`${filtered.length} user${filtered.length===1?'':'s'}`;container.querySelector('#bptUserRows').innerHTML=filtered.map(u=>`<div style="display:grid;grid-template-columns:minmax(150px,1.4fr) minmax(120px,1fr) 70px 110px 150px;gap:10px;align-items:center;padding:11px 0;border-top:1px solid #1e2b3d;font-size:11px"><div><b>${esc(u.username)}</b><small style="display:block;color:#718096;margin-top:2px">${esc(u.email)}</small></div><div><span style="color:${u.disabled?'#ff9a9a':'#55d6a0'}">${u.disabled?'Disabled':'Active'}</span><small style="display:block;color:#718096">${esc(u.lastSignIn?new Date(u.lastSignIn).toLocaleDateString('en-IN'):'Never')}</small></div><div>${u.tradeCount}</div><div>${money(u.profit)}</div><div style="display:flex;gap:5px;flex-wrap:wrap"><button class="secondary bpt-mini" data-view="${esc(u.uid)}">View</button><button class="secondary bpt-mini" data-toggle="${esc(u.uid)}" data-disabled="${u.disabled?'0':'1'}">${u.disabled?'Enable':'Disable'}</button>${u.uid===currentUid()?'':'<button class="danger bpt-mini" data-delete="'+esc(u.uid)+'">Delete</button>'}</div></div>`).join('')||'<div style="padding:24px;text-align:center;color:#8997aa">No users found.</div>';container.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>userDetails(x.dataset.view));container.querySelectorAll('[data-toggle]').forEach(x=>x.onclick=()=>toggleUser(x.dataset.toggle,x.dataset.disabled==='1'));container.querySelectorAll('[data-delete]').forEach(x=>{const u=list.find(z=>z.uid===x.dataset.delete);x.onclick=()=>deleteUser(x.dataset.delete,u?.username)})}
  function currentUid(){return window.__bptAdminUid||''}
  async function adminDashboard(){
    const b=openModal('<button class="close" data-close type="button">×</button><div style="display:flex;justify-content:space-between;align-items:center;gap:10px"><div><h3 style="margin:0">🛡️ Admin Dashboard</h3><p style="color:#8997aa;font-size:12px;margin:5px 0 0">Users, performance and app administration</p></div><button id="bptSendAnn" class="primary" type="button">📢 Announcement</button></div><div id="bptAdminBody" style="margin-top:18px"><div style="color:#8997aa">Loading admin data…</div></div>');closeOnBackdrop(b);b.querySelector('#bptSendAnn').onclick=sendAnnouncement;
    try{const r=adminCache||(adminCache=await call('getAdminDashboard'));const c=r.counts||{};const body=b.querySelector('#bptAdminBody');body.innerHTML=`<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:8px"><div class="bpt-stat"><small>Users</small><b>${c.users||0}</b></div><div class="bpt-stat"><small>Active</small><b>${c.active||0}</b></div><div class="bpt-stat"><small>Trades</small><b>${c.trades||0}</b></div><div class="bpt-stat"><small>Total booked profit</small><b>${money(c.profit)}</b></div></div><div style="margin-top:16px;display:flex;gap:8px;align-items:center"><input id="bptUserSearch" placeholder="Search users…" style="flex:1"><span id="bptUserCount" style="color:#8997aa;font-size:11px"></span></div><div style="margin-top:12px;overflow:auto"><div style="min-width:650px"><div style="display:grid;grid-template-columns:minmax(150px,1.4fr) minmax(120px,1fr) 70px 110px 150px;gap:10px;padding:8px 0;color:#718096;font-size:10px"><span>User</span><span>Status</span><span>Trades</span><span>Profit</span><span>Actions</span></div><div id="bptUserRows"></div></div></div>`;renderUsers(r.users||[],body);body.querySelector('#bptUserSearch').oninput=()=>renderUsers(r.users||[],body)}catch(e){b.querySelector('#bptAdminBody').innerHTML=`<div style="color:#ff9a9a">Admin backend is not connected yet. ${esc(e.message||'Deploy the Firebase Functions and refresh.')}</div>`}}
  async function installUsage(){try{const st=await authState();if(!st.user)return;const [a,,fs]=await mods();const db=fs.getFirestore(a.getApps()[0]);let id=localStorage.getItem('bpt-install-id');if(!id){id=crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);localStorage.setItem('bpt-install-id',id)}await fs.setDoc(fs.doc(db,'users',st.user.uid,'usage','installation'),{installId:id,lastSeen:fs.serverTimestamp(),platform:navigator.platform||'',language:navigator.language||''},{merge:true})}catch(e){}}
  async function setupMenu(){if(booted)return;booted=true;try{const st=await authState();if(!st.user){return}window.__bptAdminUid=st.user.uid;isAdmin=st.admin;await installUsage();const old=document.getElementById('bptMenuButton');if(!old)return;const original=old.onclick;old.onclick=async()=>{if(document.querySelector('.app-drawer'))return original?.();document.querySelector('.app-drawer')?.remove();const d=document.createElement('div');d.className='app-drawer';d.style.cssText='position:fixed;inset:0;z-index:9999;background:#000b';d.innerHTML='<aside style="width:min(330px,88vw);height:100%;background:#0c141f;border-right:1px solid #2a3a51;padding:22px;box-shadow:20px 0 60px #0008"><button id="bptAdminMenuClose" class="icon" type="button" style="float:right">×</button><h2 style="margin:4px 0 6px;font-size:20px">Menu</h2><p style="color:#8997aa;font-size:11px">Account and app tools</p><div style="margin-top:22px;display:grid;gap:8px"><button id="bptAdminAccount" class="secondary" type="button" style="text-align:left">👤 Account</button><button id="bptAdminMailbox" class="secondary" type="button" style="text-align:left">📬 Mailbox</button>${isAdmin?'<button id="bptAdminOpen" class="secondary" type="button" style="text-align:left">🛡️ Admin</button>':''}</div></aside>';document.body.appendChild(d);d.querySelector('#bptAdminMenuClose').onclick=()=>d.remove();d.querySelector('#bptAdminAccount').onclick=()=>document.getElementById('bptAccountButton')?.click();d.querySelector('#bptAdminMailbox').onclick=mailbox;if(isAdmin)d.querySelector('#bptAdminOpen').onclick=adminDashboard;d.onclick=e=>{if(e.target===d)d.remove()}}}catch(e){}}
  function styles(){if(document.getElementById('bptAdminStyles'))return;const s=document.createElement('style');s.id='bptAdminStyles';s.textContent='.bpt-stat{padding:11px;border:1px solid #243247;border-radius:12px;background:#0e1927}.bpt-stat small{display:block;color:#718096;font-size:9px}.bpt-stat b{display:block;margin-top:4px;font-size:13px}.bpt-mini{padding:6px 8px!important;font-size:10px!important}.danger{border:1px solid #743a43!important;color:#ff9a9a!important;background:#25151a!important}#bptAdminBody input,#bptAdminBody textarea,.modal input,.modal textarea{box-sizing:border-box}';document.head.appendChild(s)}
  async function start(){if(document.documentElement.dataset.bptAdminModule)return;document.documentElement.dataset.bptAdminModule='1';styles();let tries=0;const t=setInterval(async()=>{if(document.getElementById('bptMenuButton')){clearInterval(t);await setupMenu()}if(++tries>80)clearInterval(t)},250)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
